Add loading indicator for workspace zones
effectivemade/labs-office-elevator pull request #246
Opened 2024-04-04 16:37 UTC by Red1tum

This pr adds loading indicator until we receive data from server. I also changed modal's interface to make it more consistent(make it look like one from book period).
It also contains changes to zone selection from Artem.

2024-04-05 03:02 UTC, UserNameMax requested changes
I don't understand, why zones and meeting rooms is union

2024-04-05 03:02 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/useCase/WorkspacesUseCase.kt
> +    suspend fun getAllWorkspaces() =
Why combine zone and meeting rooms?

2024-04-06 07:09 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt
> +                    val zones = getState().allZonesList.workspaces[intent.selectedType.type]?: listOf()
В контексте этой фичи, так делать можно

2024-04-06 07:10 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/models/WorkSpace.kt
> +        isSelected = false,
Пришло требование, чтобы по дефолту переговорки не были выбраны

2024-04-06 07:11 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/useCase/WorkspacesUseCase.kt
> +    suspend fun getAllWorkspaces() =
В контексте нашего аппа - это одинаковые вещи

2024-04-06 07:14 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/BookingMainContentScreen.kt
> +                if (isErrorLoadingWorkspaceZones) {
с `when`  было бы более читаемо. Плюс вынеси эти стэйты в отдельные `@Composable` фунайкции

2024-04-06 07:17 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt
> +                                val isError = response.error.error.code != 400
такое должно быть в `useCase`

2024-04-06 07:19 UTC, gull192 requested changes
Исправь недочеты

2024-04-09 08:36 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/WorkspacesErrorButton.kt
> +fun WorkspacesErrorButton(modifier: Modifier = Modifier) {
Почему не использовать стандартный `Button` из `Matherial`? И Clickable колбеки лучше передавать параметром в функцию, а не через `Modifier` :)
Исправь это

2024-04-09 08:38 UTC, gull192 commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/WorkspacesErrorButton.kt
> +fun WorkspacesErrorButton(modifier: Modifier = Modifier) {
Получится что-то типо
```
@Composable
fun CrazyButton(onClick: ()-> Unit) {
  Button (onClick = onClick){ //Content }
  }
  ```

2024-04-09 08:40 UTC, gull192 approved these changes
Еще раз протести, поправь то, что написано в комментариях, и можешь мержить

2024-04-09 10:46 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/WorkspaceZonesErrorButton.kt
> +        Row(
DRY

2024-04-09 10:49 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/WorkspacesErrorButton.kt
> +        Row(
DRY

2024-04-10 10:57 UTC, UserNameMax approved these changes

2024-04-10 10:57 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/ErrorButton.kt
> +fun ErrorButton(
Perfect

2024-04-11 15:52 UTC, merged