Gray loading slots
effectivemade/labs-office-elevator pull request #261
Opened 2024-05-07 10:49 UTC by plumsoftware

2024-05-08 18:25 UTC, UserNameMax requested changes

2024-05-08 18:25 UTC, UserNameMax commented on tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/slotComponent/store/SlotStoreFactory.kt
> +                    val indexInMultiSlot = mainSlot!!.subSlots.indexOf(uiSlot)
What with null safety?

2024-05-21 10:43 UTC, UserNameMax requested changes
Application not build. Build your code before push next time

2024-05-21 11:05 UTC, plumsoftware commented
You can see a preview in [card](https://www.notion.so/effectiveband/f3920d143a8d4ac0a8315b6722775f22?v=1b85aa1792db4c53926e27c36d888ea1)

2024-05-22 11:41 UTC, UserNameMax approved these changes
remove comment code

2024-05-22 11:41 UTC, UserNameMax commented on tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/slotComponent/SlotView.kt
> +                text = "Загрузка слота на время: ${slot.start.toFormattedString("HH:mm")} - ${slot.finish.toFormattedString("HH:mm")}", //TODO() replace this hard str
remove todo

2024-05-22 11:41 UTC, UserNameMax commented on tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/slotComponent/store/SlotStoreFactory.kt
> +//                Log.i("TAG", state.slots.toString())
clean code

2024-05-22 13:45 UTC, Red1tum approved these changes

2024-05-24 06:07 UTC, merged