EO-605, EO-612 TvApp: remove interns from stories, fix anniversary checks
effectivemade/labs-office-elevator pull request #280
Opened 2024-07-09 11:13 UTC by Red1tum

Had to bump compose-android version, otherwise it wouldn't compile.

2024-07-10 15:11 UTC, UserNameMax approved these changes

2024-07-10 15:11 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/use_cases/EventStoryDataUseCase.kt
> +                .filter { it.employment == "Band" && it.status == "Active" }
А чё вы Intern обидели? Не хотите показывать их праздники?

2024-07-17 03:33 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/model/notion/EmployeeInfoEntity.kt
> +    return oneMonthCheck.isSameDay(employeeStartDate) && employment == "Band"
Если часто используете одни и те же строки в логике, то выносите их в константы, а ещё лучше в enum и sealed

2024-07-17 03:35 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/repository/notion/impl/EmployeeInfoRepositoryImpl.kt
> +                            "Band",
Используйте именованные параметры, а то не понятно, что значит `"Band"`. Он ганкстер и состоит в банде?

2024-07-17 03:53 UTC, UserNameMax requested changes

2024-07-17 03:53 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/components/StoryContent.kt
> +                        fontSize = 46.sp,
Повторяющиеся размеры лучше куда-то вынести

2024-07-17 03:53 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/components/StoryContent.kt
> +                if (employeeInfo.employment == "Intern") {
Я бы у EmployeeInfo сделал свойство `isIntern`
`val isIntern get() = employment == EmploymentType.INTERN`

2024-07-17 03:53 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/components/StoryContent.kt
>                  if (isAnnualAnnualAnniversary) {
Тут на when стоит заменить. А то cast ещё и без проверки выглядит не ок

2024-07-17 03:53 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/eventStory/models/EventInfoUI.kt
>  sealed class EmployeeInfoUI(
В классе можно определить поле, и потом заоверайдить его в конструкторе наследника, чтобы у вас не было два одинаковых поля с разными названиями

2024-07-25 18:08 UTC, UserNameMax approved these changes

2024-07-25 18:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/repository/notion/impl/EmployeeInfoRepositoryImpl.kt
Зачем поддерживаете Deprecated класс?

2024-07-25 18:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/components/StoryContent.kt
> +                                employeeInfo.yearsInCompany,
Уберите в ресурсы

2024-07-25 18:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/eventStory/models/EventInfoUI.kt
> +    open val isIntern: Boolean,
```
sealed class Parent {
    val field: Int
}

data class Child(override val field: Int)
```

2024-07-26 05:49 UTC, Red1tum commented on tvApp/src/main/java/band/effective/office/tv/screen/eventStory/models/EventInfoUI.kt
> +    open val isIntern: Boolean,
без ```open``` будет ошибка ```'field' in 'Parent' is final and cannot be overridden.```
[Вот этот код в плейграунде.](https://pl.kotl.in/uCv55UT9R)

2024-07-26 07:07 UTC, merged