EO-621 Moblie: fix avatar's url not being sent after authorization
effectivemade/labs-office-elevator pull request #282
Opened 2024-07-11 08:23 UTC by Red1tum

2024-07-12 09:06 UTC, UserNameMax requested changes

2024-07-12 09:06 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/AuthorizationRepositoryImpl.kt
> +                if (imageUrl != null) user.copy(imageUrl = imageUrl)
Это в маппере должно быть

2024-07-15 08:24 UTC, UserNameMax commented on composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/models/User.kt
> +        imageUrl = imageUrl ?: avatarUrl,
Может лучше наоборот? `avatarUrl.takeIf{it.notEmpty()} ?: imageUrl`. Мне кажется стоит отдовать предпотение информации с нашего сервера, а уже во вторую очередь гуглу. Это даст нам больше контроля

2024-07-17 03:20 UTC, UserNameMax approved these changes

2024-07-18 06:41 UTC, csupernova approved these changes

2024-07-18 06:47 UTC, merged