EO-620, TvApp: Supernova rating
effectivemade/labs-office-elevator pull request #289
Opened 2024-08-27 07:33 UTC by csupernova

This PR contains implementation of supernova rating as EventStory on TV of employees.

2024-08-27 13:08 UTC, UserNameMax requested changes

2024-08-27 13:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/supernova/components/TopSupernova.kt
> +fun TopSupernova(users: List<List<SupernovaUserUi>>) {
Весь ui суперновой это копипаста рейтинга спорта. Зачем дублировать код? Старайтесь хоть сколько то соблюдать DRY
Этот метод можно с лёгкостью обощить:
```
@Composable
fun <T> Top(users: List<List<T>>, item: @Composable (T) -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxSize(),
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        users.forEach { list ->
            Column(
                verticalArrangement = Arrangement.spacedBy(20.dp)
            ) {
                list.forEach { item ->
                    item(item)
                }
            }
        }
    }
}
```

Думаю, что и UI моделки можно объеденить и вообще избавится от дженерика.
Особо сильно режет глаз, когда дублируются title

2024-08-27 13:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/eventStory/EventStoryViewModel.kt
> +            ) { notionData, duolingoInfo, clockifyInfo, supernovaInfo ->
Это всё должно быть в EventStoryDataCombinerUseCase. Там слово Combiner не спроста в название

2024-08-27 13:08 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/eventStory/EventStoryViewModel.kt
> +            ) { notionData, duolingoInfo, clockifyInfo, supernovaInfo ->
Лучше разделить получение и маппинг данных из разных источников по разным репозиториям и use case

2024-08-30 07:48 UTC, UserNameMax approved these changes

2024-08-30 07:48 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/model/DomainModel.kt
> +abstract class DomainModel
1) Непонятное название
2) Наверное это sealed
3) До этого была же какая-то модель?

2024-08-30 07:48 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/use_cases/EventStoryDataCombinerUseCase.kt
> +    fun getMessagesFromMattermost() = MessageQueue.secondQueue.toListOfEmployeeInfo()
Этот метод никогда не используется

2024-08-30 07:48 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/use_cases/SupernovaDataUseCase.kt
> +class SupernovaDataUseCase @Inject constructor(
Use case для story однотипные весьма, я бы подумал как можно их "склеить"

2024-08-30 07:48 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/supernova/SupernovaScreen.kt
> +fun SupernovaScreen(
Экран суперновой и спорта по вёрстке тоже очень похожи и строки в них тоже похожи

2024-08-30 10:05 UTC, csupernova commented on tvApp/src/main/java/band/effective/office/tv/domain/model/DomainModel.kt
> +abstract class DomainModel
я создал этот класс, который наследуют классы, участвующие в реализации сторис, чтобы из combinerUseCase во ViewModel можно было "разделить" типы сторис и преобразовать их для UI. До этого они сразу преобразовывались в combinerUseCase, но это неправильно с точки зрения предназначения слоя domain, поэтому пришлось как-то их "обобщить", чтобы извлекать их внутри ViewModel

2024-09-10 09:57 UTC, UserNameMax requested changes
DomainModel плохое имя класса

2024-09-10 09:57 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/autoplayController/AutoplayController.kt
> +        if (state.value.screensList.size == 0) {
есть isEmpty

2024-09-10 09:57 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/use_cases/EventStoryDataCombinerUseCase.kt
> +                            val domainModels: MutableList<DomainModel> = mutableListOf()
Есть принцип кричащей архитектуры, когда по названию класса понятно для чего он. Имя класса DomainModel не о чем не говорит, поэтому это плохое имя

2024-09-20 06:22 UTC, UserNameMax approved these changes

2024-09-20 06:22 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/screen/components/EventStoryScreenContent.kt
> +            when (event) {
можно написать метод который достаёт сторку из sealed 

```
//in some place 
fun EventsInfo.photoUrl() = when(this) {
                is DuolingoUserInfo -> photo
                is SportUserInfo -> photo
                is SupernovaUserInfo -> photoUrl
}

// in composable
eventInfo.map{it.photoUrl()}.forEach{
val request = ImageRequest.Builder(context)
                .data(it)
                .memoryCachePolicy(CachePolicy.DISABLED)
                .decoderFactory { _, _, _ ->
                    Decoder { DecodeResult(ColorDrawable(Color.BLACK), false) }
                }
                .build()
            context.imageLoader.enqueue(request)
}
```

2024-09-20 06:22 UTC, UserNameMax commented on tvApp/src/main/java/band/effective/office/tv/domain/model/StoryDomainModel.kt
> +abstract class StoryDomainModel
Всё равно выглядит сомнитеельнооооо. Это  sealed interface как будто должно быть

2024-10-14 04:20 UTC, merged